### ISSUE TITLE
Heatmap Colors Scaling Issue

### ISSUE THREAD

**Issue by rridihalgh** [Microsoft/UE4TelemetryVisualizer#6]
When changing the Maximum value in the Type Range to a value below the actual maximum, Heatmap "cell" colors that have actual values above the new maximum will not scale correctly.

**To Reproduce**
1. Select an Event type to heatmap
2. Generate the heatmap
3. change the maximum range value to something (significantly) less that the generated value
4. Observe cells with colors that look incorrect as though the color scaling goes "over" the maximum color

**Expected behavior**
Every cell in a heatmap will have colors that fall between the min and max color values

![image](https://user-images.githubusercontent.com/13008233/56389312-18e7f700-61de-11e9-8595-17364bbc517b.png)

From the code it looks as though the values to select color range can go over 1.0 because of the way they are clamped.   The code in question is from TelemetryVisualizerTab.cpp (around lines 1090 thru 1150) where the tempColorValue is being clamped (there are 4 instances of this clamping):
     tempColorValue = FMath::Max(tempColorValue, 0.f);
     tempColorValue = FMath::Min(tempColorValue, (float)m_heatmapMaxValue);

The incoming tempColorValue can (and will when max range is smaller than actual) be above 1.0.  Clamping clamping to 1.0 should fix the problem as such: 
     tempColorValue = FMath::Max(tempColorValue, 0.f);
     tempColorValue = FMath::Min(tempColorValue, 1.f);

If the value is properly clamped between 0.0 and 1.0 then the scaling of the color will be proper and modified max values will show as actual max color from this call:
tempActor->AddEvent(parts[i].GetCenter(), orientation[i], **m_heatmapColor.GetColorFromRange(tempColorValue)**, m_heatmapShapeType, scaledHeatmapSize, tempValue);

**Comment by Lifespan** [comment]
Fixed with [recent pull](https://github.com/Microsoft/UE4TelemetryVisualizer/pull/9)
