### ISSUE TITLE
Heatmap Colors Scaliing Issue #2

### ISSUE THREAD

**Issue by rridihalgh** [Microsoft/UE4TelemetryVisualizer#7]
**Describe the bug**
There is an issue with how the heatmap colors are scaling between low and high value colors due to an unsigned value error in calculating the range between colors.

**To Reproduce**
1. Create a heatmap
2. Change the low and high colors
3. depending on the colors selected, the newly generated heatmap colors may seem off

**Expected behavior**
The heatmap colors scale between high and low linearly in the R, G, B, and Alpha values

The range values that are being calculated between the low and high colors are only ever positive values because the ColorRange struct uses uint8 values for the ranges:
struct ColorRange
{
	uint8 A;
	uint8 B;
	uint8 G;
	uint8 R;
};

The range is created be subtracting the low color value members from the high color value members, but that value could be a negative value.  eg. if my high color is r:255, g:0, b:0, a:128 (default) and low color is r:0, g:255, b:0, a:128 (default), the resulting range values are r:255, g:1, b:0, a:0 when the should be r:255, **g:-255**, b:0, a:0

So when the range is used to scale between low and high the colors right now are not as intended.

**Comment by Lifespan** [comment]
Fixed with [recent pull](https://github.com/Microsoft/UE4TelemetryVisualizer/pull/9)
