### ISSUE TITLE
Heatmap cell Value is incorrect

### ISSUE THREAD

**Issue by rridihalgh** [Microsoft/UE4TelemetryVisualizer#8]
**Describe the bug**
When using value or value-bar to generate heatmap, the cell values get added up when they should use the average value of all the events within that cell.  The effect of this is cells with multiple events will have the wrong and potentially way out of range value.  for example, using FPS events, if I'm at a steady 30 fps and I have 3 events in a cell all with value of 30 fps, the actual cell value will be calculated as 90, not 30.

**To Reproduce**
1. create a heatmap with cells that have multiple events in them
2. generate and note the max value reported will be higher than the highest individual event value in the event set

**Expected behavior**
When the heatmap calculates the value for a cell it should be the average of all the values of the events in that cell.  EG. if I'm using event values of frames per second and I have a steady 30fps, in a cell with multiple events I should have a cell value of 30, not the value of all the events added up.

The solution to this is to simply average the values within a cell.  Take the current added up value and divide by the number of events in the cell.

**Comment by Lifespan** [comment]
Fixed with [recent pull](https://github.com/Microsoft/UE4TelemetryVisualizer/pull/9)
